"""initial nine tables

Revision ID: 58a2acbd80ba
Revises: 
Create Date: 2026-08-30 23:30:15.095181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '58a2acbd80ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector backs the FastRP persona embeddings in Phase 4. Created here so a
    # fresh database is ready before any code needs the type.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Postgres ENUMs are schema objects, not table-scoped. SQLAlchemy emits an
    # inline CREATE TYPE on first use and never drops it, which makes the
    # migration non-reversible: downgrade leaves signal_root behind and the next
    # upgrade fails with DuplicateObject. Create it explicitly here, tell the
    # column not to re-create it, and drop it in downgrade().
    signal_root = postgresql.ENUM(
        "identity_key", "financial", "infra", "linguistic", "temporal", "social",
        name="signal_root",
    )
    signal_root.create(op.get_bind(), checkfirst=True)

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assignee', sa.String(length=128), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('extractor', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_entity_kind_value')
    )
    op.create_index('ix_entity_kind', 'entities', ['kind'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'handle', name='uq_persona_market_handle')
    )
    op.create_index('ix_persona_actor', 'personas', ['actor_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.String(length=128), nullable=False),
    sa.Column('root', postgresql.ENUM('identity_key', 'financial', 'infra', 'linguistic', 'temporal', 'social', name='signal_root', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('negative', sa.Boolean(), nullable=False),
    sa.Column('cap', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_pair', 'signals', ['pair_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('requires_key', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_scan', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_24h', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('ed25519_pubkey', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=66), nullable=True),
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=True),
    sa.Column('pubkey', sa.String(length=128), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'seq', name='uq_audit_case_seq')
    )
    op.create_index('ix_audit_case', 'audit_records', ['case_id'], unique=False)
    op.create_table('pair_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.String(length=128), nullable=False),
    sa.Column('persona_a', sa.Integer(), nullable=True),
    sa.Column('persona_b', sa.Integer(), nullable=True),
    sa.Column('p_raw', sa.Float(), nullable=True),
    sa.Column('p_calibrated', sa.Float(), nullable=True),
    sa.Column('roots_used', sa.JSON(), nullable=True),
    sa.Column('roots_collapsed', sa.JSON(), nullable=True),
    sa.Column('negatives', sa.JSON(), nullable=True),
    sa.Column('trail', sa.JSON(), nullable=True),
    sa.Column('naive_stack', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_a'], ['personas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_b'], ['personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair_id', name='uq_pairscore_pair')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('raw_pgp', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_persona_ts', 'posts', ['persona_id', 'ts'], unique=False)
    op.create_table('seals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('root', sa.String(length=66), nullable=False),
    sa.Column('leaf_count', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('is_public_chain', sa.Boolean(), nullable=False),
    sa.Column('anchored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root', name='uq_seal_root')
    )
    # ### end Alembic commands ###



    # Seed the source inventory so /sources reports real rows on a fresh clone.
    op.execute(
        """
        INSERT INTO sources (name, kind, requires_key, enabled, items_24h, created_at, updated_at)
        VALUES
          ('hackernews',    'osint',   false, true, 0, now(), now()),
          ('google_news',   'osint',   false, true, 0, now(), now()),
          ('reddit',        'osint',   false, true, 0, now(), now()),
          ('crtsh',         'infra',   false, true, 0, now(), now()),
          ('shodan',        'infra',   true,  true, 0, now(), now()),
          ('mempool_space', 'chain',   false, true, 0, now(), now()),
          ('etherscan',     'chain',   true,  true, 0, now(), now()),
          ('dnm_archives',  'dataset', false, true, 0, now(), now()),
          ('kaggle_agora',  'dataset', false, true, 0, now(), now())
        ON CONFLICT (name) DO NOTHING
        """
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seals')
    op.drop_index('ix_post_persona_ts', table_name='posts')
    op.drop_table('posts')
    op.drop_table('pair_scores')
    op.drop_index('ix_audit_case', table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_index('ix_signal_pair', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_persona_actor', table_name='personas')
    op.drop_table('personas')
    op.drop_index('ix_entity_kind', table_name='entities')
    op.drop_table('entities')
    op.drop_table('cases')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS signal_root")
